### PR TITLE
build: expose internals

### PR DESCRIPTION
**Pull request by Kikobeats**
useful for debugging

### CODE REVIEW

**Comment by gajus** [comment]
Goes against my policy of limiting API surface to only what's necessary.

**Comment by Kikobeats** [comment]
can't debug if the value is unaccesible

**Comment by gajus** [comment]
`vim ./node_modules/http-terminator/dist/*` :-)

**Comment by Kikobeats** [comment]
debug a thing, code at production server is a totally different thing and not always possible (e.g. AWS Lambda)

**Pull request closed without merging**
